# permissions for end users to edit mastodons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mastodon-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mastodon-operator
    app.kubernetes.io/part-of: mastodon-operator
    app.kubernetes.io/managed-by: kustomize
  name: mastodon-editor-role
rules:
- apiGroups:
  - mastodon.k8s.mulliken.net
  resources:
  - mastodons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mastodon.k8s.mulliken.net
  resources:
  - mastodons/status
  verbs:
  - get
