---
- name: Create cloudflared tunnel deployment
  kubernetes.core.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-cloudflared-tunnel'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: 1
        selector:
          matchLabels:
            app.kubernetes.io/name: cloudflared-tunnel
            app.kubernetes.io/instance: '{{ ansible_operator_meta.name }}'
            app.kubernetes.io/part-of: mastodon-operator
            app.kubernetes.io/managed-by: kustomize
            app.kubernetes.io/created-by: mastodon-operator
            app.kubernetes.io/component: cloudflared-tunnel
        template:
          metadata:
            labels:
              app.kubernetes.io/name: cloudflared-tunnel
              app.kubernetes.io/instance: '{{ ansible_operator_meta.name }}'
              app.kubernetes.io/part-of: mastodon-operator
              app.kubernetes.io/managed-by: kustomize
              app.kubernetes.io/created-by: mastodon-operator
              app.kubernetes.io/component: cloudflared-tunnel
          spec:
            containers:
              - name: cloudflared-tunnel
                image: '{{ cloudflared_image }}'
                imagePullPolicy: Always
                args:
                  - tunnel
                  - run
                  - --token
                  - "{{ cloudflared_tunnel_token }}"
                resources:
                  limits:
                    cpu: 100m
                    memory: 128Mi
                  requests:
                    cpu: 50m
                    memory: 64Mi
